#!/bin/bash
export to_number=18018026412
export cid_number=18017689999
export key_file_name=captioncall_verified_callerid_prod.key
export key_alias=captioncall_verified_callerid_prod
export sip_username=mrw_softphone_3
export sip_password=alianza
